apiVersion: apps/v1
kind: Deployment
metadata:
  name: etl-app-deployment
  labels:
    app: etl-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etl-app
  template:
    metadata:
      labels:
        app: etl-app
    spec:
      containers:
      - name: etl-container
        image: cloudwaveacr26077.azurecr.io/etl-app:93a9478085b9469b276893d35f700b58a2255819
        resources:
          requests:
            cpu: "250m" # 0.25 vCPU
            memory: "256Mi"
          limits:
            cpu: "1"      # 1 vCPU - As per requirement
            memory: "1Gi" # 1 GiB - As per requirement
        volumeMounts:
        - name: output-storage
          mountPath: /app/output
      volumes:
      - name: output-storage
        persistentVolumeClaim:
          claimName: etl-output-pvc