apiVersion: batch/v1
kind: Job
metadata:
  # The 'generateName' field tells Kubernetes to use this as a prefix
  # and to automatically append a unique random suffix for each new Job
  generateName: etl-app-run-
spec:
  # The template for the pod is almost identical to what was in the Deployment.
  template:
    spec:
      containers:
      - name: etl-container
        # This will be updated by the CI pipeline
        image: cloudwaveacr26077.azurecr.io/etl-app:fc0013fd9700e3075c69dfbf77c2032ba4cc1126
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
        volumeMounts:
        - name: output-storage
          mountPath: /app/output
      volumes:
      - name: output-storage
        persistentVolumeClaim:
          claimName: etl-output-pvc
      
      # This is crucial for Jobs. It tells the Job not to restart a pod
      # if it exits successfully. It will only restart if it fails (non-zero exit code).
      restartPolicy: OnFailure
  
  # Optional: Clean up the Job and Pod after it's done.
  # After 1 hour (3600 seconds), Kubernetes will automatically delete the completed Job.
  ttlSecondsAfterFinished: 3600