apiVersion: batch/v1
kind: Job
metadata:
  # The name is generated to be unique for each run to avoid conflicts.
  # Argo CD can help manage this, or we can add a unique suffix.
  # For simplicity, we'll let the CI pipeline handle this later if needed.
  name: etl-app-run
spec:
  # The template for the pod is almost identical to what was in the Deployment.
  template:
    spec:
      containers:
      - name: etl-container
        # This will be updated by the CI pipeline
        image: placeholder/image:latest 
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
        volumeMounts:
        - name: output-storage
          mountPath: /app/output
      volumes:
      - name: output-storage
        persistentVolumeClaim:
          claimName: etl-output-pvc
      
      # This is crucial for Jobs. It tells the Job not to restart a pod
      # if it exits successfully. It will only restart if it fails (non-zero exit code).
      restartPolicy: OnFailure
  
  # Optional: Clean up the Job and Pod after it's done.
  # After 1 hour (3600 seconds), Kubernetes will automatically delete the completed Job.
  ttlSecondsAfterFinished: 3600